options:
  threads:
    default: 10
    type: int
    description: |
      Number of concurrent threads that will perform the test.
  clients:
    default: 8
    type: int
    description: |
      Number of concurrent clients submitting transactions involved in the testing.
  duration:
    default: 0
    type: int
    description: |
      Duration of the test in seconds. If set to 0, it does not stop.
  workload_name:
    default: "nyc_taxis"
    type: string
    description: |
      Name of the workload to use.